/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as BuildsIndexRouteImport } from './routes/builds.index'
import { Route as BuildsBuildIdRouteImport } from './routes/builds.$buildId'
import { Route as TasksTaskIdConsoleRouteImport } from './routes/tasks.$taskId.console'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsBuildIdRoute = BuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdConsoleRoute = TasksTaskIdConsoleRouteImport.update({
  id: '/tasks/$taskId/console',
  path: '/tasks/$taskId/console',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workers': typeof WorkersRoute
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/builds/': typeof BuildsIndexRoute
  '/tasks/$taskId/console': typeof TasksTaskIdConsoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workers': typeof WorkersRoute
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/builds': typeof BuildsIndexRoute
  '/tasks/$taskId/console': typeof TasksTaskIdConsoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workers': typeof WorkersRoute
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/builds/': typeof BuildsIndexRoute
  '/tasks/$taskId/console': typeof TasksTaskIdConsoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workers'
    | '/builds/$buildId'
    | '/builds/'
    | '/tasks/$taskId/console'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/workers' | '/builds/$buildId' | '/builds' | '/tasks/$taskId/console'
  id:
    | '__root__'
    | '/'
    | '/workers'
    | '/builds/$buildId'
    | '/builds/'
    | '/tasks/$taskId/console'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkersRoute: typeof WorkersRoute
  BuildsBuildIdRoute: typeof BuildsBuildIdRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
  TasksTaskIdConsoleRoute: typeof TasksTaskIdConsoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/': {
      id: '/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$buildId': {
      id: '/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/builds/$buildId'
      preLoaderRoute: typeof BuildsBuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/console': {
      id: '/tasks/$taskId/console'
      path: '/tasks/$taskId/console'
      fullPath: '/tasks/$taskId/console'
      preLoaderRoute: typeof TasksTaskIdConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkersRoute: WorkersRoute,
  BuildsBuildIdRoute: BuildsBuildIdRoute,
  BuildsIndexRoute: BuildsIndexRoute,
  TasksTaskIdConsoleRoute: TasksTaskIdConsoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
