run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
  disable:
    - typecheck

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (net.Conn).Close
      - (*google.golang.org/grpc.ClientConn).Close
      - (*net/http.Server).Shutdown
      - encoding/json.(*Encoder).Encode
  staticcheck:
    checks:
      - all
      - "-SA1019"  # Ignore deprecation warnings (grpc.DialContext, etc.)

issues:
  exclude-rules:
    # Exclude errcheck in test files
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
    # Exclude errcheck for common fire-and-forget patterns
    - linters:
        - errcheck
      text: "Error return value of `cmd.Help` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `pem.Encode` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `.*Execute` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `k.hasher"
    - linters:
        - errcheck
      text: "Error return value of `s.Delete` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `.*Encode` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `c.conn.Set.*Deadline` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `c.conn.WriteMessage` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `w.Write` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `e.client.Container"
    - linters:
        - errcheck
      text: "Error return value of `s.registry"
    - linters:
        - errcheck
      text: "Error return value of `metricsServer.Shutdown` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `dashSrv.Stop` is not checked"
    # Exclude ineffassign for intentional patterns
    - linters:
        - ineffassign
      text: "ineffectual assignment to err"
    # Exclude staticcheck unused append (intentional pre-allocation)
    - linters:
        - staticcheck
      text: "SA4010"
